version: '3.8'

services:
  filedrop:
    image: rdnsx/filedrop
    volumes:
      - /mnt/SSS/DockerData/drop2share.de:/app/uploads
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  default:
    external:
      name: npm_default